onboarding = false

[theme]
name = "catppuccin"

auto_switch = false
[keys]
prefix = "ctrl+a"
zoom = ["super+enter", "prefix+z", "prefix+space"]
reload_config = "prefix+;"
detach = "prefix+d"
toggle_sidebar = ["prefix+b", "prefix+ctrl+b"]
# workspace
switch_workspace = "super+1..9"
previous_workspace = ["super+alt+k", "prefix+ctrl+k"]
next_workspace = ["super+alt+j", "prefix+ctrl+j"]
new_workspace = ["super+n", "prefix+n"]
rename_workspace = "prefix+."
# agent
previous_agent = ["shift+alt+k", "prefix+shift+k"]
next_agent = ["shift+alt+j", "prefix+shift+j"]
focus_agent = "prefix+1..9"
# tab
previous_tab = "super+["
next_tab = "super+]"
switch_tab = "ctrl+1..9"
new_tab = ["super+t", "prefix+t"]
rename_tab = ["prefix+,"]
# pane
focus_pane_left = ["super+h", "prefix+h", "prefix+left"]
focus_pane_down = ["super+j", "prefix+j", "prefix+down"]
focus_pane_up = ["super+k", "prefix+k", "prefix+up"]
focus_pane_right = ["super+l", "prefix+l", "prefix+right"]
close_pane = ["super+w", "prefix+x"]
split_vertical = ["super+\\", "prefix+\\"]
split_horizontal = ["super+-", "prefix+-"]

[experimental]
kitty_graphics = true

[ui]
show_agent_labels_on_pane_borders = true
prompt_new_tab_name = false
mobile_width_threshold = 100

[ui.toast]
delivery = "terminal"
delay_seconds = 1

[ui.toast.herdr]
position = "bottom-right"
