default-config:
	kitty +runpy 'from kitty.config import *; print(commented_out_default_config())' > kitty.default.conf
kitty-tab-switcher:
	wget -O kitty-tab-switcher https://raw.githubusercontent.com/OsiPog/kitty-tab-switcher/refs/heads/main/kitty-tab-switcher
	chmod +x kitty-tab-switcher
