set -U _fisher_plugins jorgebucaran/autopair.fish patrickf1/fzf.fish ilancosman/tide@v6 jorgebucaran/fisher jhillyerd/plugin-git

if not set -q _fisher_jorgebucaran_2F_autopair_2E_fish_files
    set -U _fisher_jorgebucaran_2F_autopair_2E_fish_files "~/.config/fish/plugins/functions/_autopair_backspace.fish" "~/.config/fish/plugins/functions/_autopair_insert_left.fish" "~/.config/fish/plugins/functions/_autopair_insert_right.fish" "~/.config/fish/plugins/functions/_autopair_insert_same.fish" "~/.config/fish/plugins/functions/_autopair_tab.fish" "~/.config/fish/plugins/conf.d/autopair.fish"
end

if not set -q _fisher_patrickf1_2F_fzf_2E_fish_files
    set -U _fisher_patrickf1_2F_fzf_2E_fish_files "~/.config/fish/plugins/functions/_fzf_configure_bindings_help.fish" "~/.config/fish/plugins/functions/_fzf_extract_var_info.fish" "~/.config/fish/plugins/functions/_fzf_preview_changed_file.fish" "~/.config/fish/plugins/functions/_fzf_preview_file.fish" "~/.config/fish/plugins/functions/_fzf_report_diff_type.fish" "~/.config/fish/plugins/functions/_fzf_report_file_type.fish" "~/.config/fish/plugins/functions/_fzf_search_directory.fish" "~/.config/fish/plugins/functions/_fzf_search_git_log.fish" "~/.config/fish/plugins/functions/_fzf_search_git_status.fish" "~/.config/fish/plugins/functions/_fzf_search_history.fish" "~/.config/fish/plugins/functions/_fzf_search_processes.fish" "~/.config/fish/plugins/functions/_fzf_search_variables.fish" "~/.config/fish/plugins/functions/_fzf_wrapper.fish" "~/.config/fish/plugins/functions/fzf_configure_bindings.fish" "~/.config/fish/plugins/conf.d/fzf.fish" "~/.config/fish/plugins/completions/fzf_configure_bindings.fish"
end

if not set -q _fisher_ilancosman_2F_tide_40_v6_files
    set -U _fisher_ilancosman_2F_tide_40_v6_files "~/.config/fish/plugins/functions/_tide_1_line_prompt.fish" "~/.config/fish/plugins/functions/_tide_2_line_prompt.fish" "~/.config/fish/plugins/functions/_tide_cache_variables.fish" "~/.config/fish/plugins/functions/_tide_detect_os.fish" "~/.config/fish/plugins/functions/_tide_find_and_remove.fish" "~/.config/fish/plugins/functions/_tide_fish_colorize.fish" "~/.config/fish/plugins/functions/_tide_item_aws.fish" "~/.config/fish/plugins/functions/_tide_item_bun.fish" "~/.config/fish/plugins/functions/_tide_item_character.fish" "~/.config/fish/plugins/functions/_tide_item_cmd_duration.fish" "~/.config/fish/plugins/functions/_tide_item_context.fish" "~/.config/fish/plugins/functions/_tide_item_crystal.fish" "~/.config/fish/plugins/functions/_tide_item_direnv.fish" "~/.config/fish/plugins/functions/_tide_item_distrobox.fish" "~/.config/fish/plugins/functions/_tide_item_docker.fish" "~/.config/fish/plugins/functions/_tide_item_elixir.fish" "~/.config/fish/plugins/functions/_tide_item_gcloud.fish" "~/.config/fish/plugins/functions/_tide_item_git.fish" "~/.config/fish/plugins/functions/_tide_item_go.fish" "~/.config/fish/plugins/functions/_tide_item_java.fish" "~/.config/fish/plugins/functions/_tide_item_jobs.fish" "~/.config/fish/plugins/functions/_tide_item_kubectl.fish" "~/.config/fish/plugins/functions/_tide_item_nix_shell.fish" "~/.config/fish/plugins/functions/_tide_item_node.fish" "~/.config/fish/plugins/functions/_tide_item_os.fish" "~/.config/fish/plugins/functions/_tide_item_php.fish" "~/.config/fish/plugins/functions/_tide_item_private_mode.fish" "~/.config/fish/plugins/functions/_tide_item_pulumi.fish" "~/.config/fish/plugins/functions/_tide_item_python.fish" "~/.config/fish/plugins/functions/_tide_item_ruby.fish" "~/.config/fish/plugins/functions/_tide_item_rustc.fish" "~/.config/fish/plugins/functions/_tide_item_shlvl.fish" "~/.config/fish/plugins/functions/_tide_item_status.fish" "~/.config/fish/plugins/functions/_tide_item_terraform.fish" "~/.config/fish/plugins/functions/_tide_item_time.fish" "~/.config/fish/plugins/functions/_tide_item_toolbox.fish" "~/.config/fish/plugins/functions/_tide_item_vi_mode.fish" "~/.config/fish/plugins/functions/_tide_item_zig.fish" "~/.config/fish/plugins/functions/_tide_parent_dirs.fish" "~/.config/fish/plugins/functions/_tide_print_item.fish" "~/.config/fish/plugins/functions/_tide_pwd.fish" "~/.config/fish/plugins/functions/_tide_remove_unusable_items.fish" "~/.config/fish/plugins/functions/_tide_sub_bug-report.fish" "~/.config/fish/plugins/functions/_tide_sub_configure.fish" "~/.config/fish/plugins/functions/_tide_sub_reload.fish" "~/.config/fish/plugins/functions/fish_mode_prompt.fish" "~/.config/fish/plugins/functions/fish_prompt.fish" "~/.config/fish/plugins/functions/tide" "~/.config/fish/plugins/functions/tide.fish" "~/.config/fish/plugins/conf.d/_tide_init.fish" "~/.config/fish/plugins/completions/tide.fish"
end

if not set -q _fisher_jorgebucaran_2F_fisher_files
    set -U _fisher_jorgebucaran_2F_fisher_files "~/.config/fish/plugins/functions/fisher.fish" "~/.config/fish/plugins/completions/fisher.fish"
end

if not set -q _fisher_jhillyerd_2F_plugin_2D_git_files
    set -U _fisher_jhillyerd_2F_plugin_2D_git_files "~/.config/fish/plugins/functions/__git.branch_has_wip.fish" "~/.config/fish/plugins/functions/__git.current_branch.fish" "~/.config/fish/plugins/functions/__git.default_branch.fish" "~/.config/fish/plugins/functions/__git.delete_branches.fish" "~/.config/fish/plugins/functions/__git.destroy.fish" "~/.config/fish/plugins/functions/__git.init.fish" "~/.config/fish/plugins/functions/gbage.fish" "~/.config/fish/plugins/functions/gbda.fish" "~/.config/fish/plugins/functions/gdv.fish" "~/.config/fish/plugins/functions/gignored.fish" "~/.config/fish/plugins/functions/glp.fish" "~/.config/fish/plugins/functions/grename.fish" "~/.config/fish/plugins/functions/grt.fish" "~/.config/fish/plugins/functions/gtest.fish" "~/.config/fish/plugins/functions/gtl.fish" "~/.config/fish/plugins/functions/gunwip.fish" "~/.config/fish/plugins/functions/gwip.fish" "~/.config/fish/plugins/conf.d/git.fish"
end
