abbr --add ypp "yadm commit -s && yadm push"
abbr --add yp "yadm push"
abbr --add yd "yadm diff"
abbr --add yl "yadm pull"
abbr --add yll "yadm reset --hard HEAD && yadm pull"
abbr --add yss "yadm status"
abbr --add yg "lazygit -ucd ~/.local/share/yadm/lazygit -w ~ -g ~/.local/share/yadm/repo.git"
abbr --add yig "lazygit -ucd ~/.local/share/yadm/lazygit -w ~ -g ~/.local/share/yadm-private/repo.git"
abbr --add yug "lazygit -ucd ~/.local/share/yadm/lazygit -w ~ -g ~/.local/share/yadm-public/repo.git"
