#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

if [ "$SENDER" = "aerospace_service_mode_enabled_changed" ]; then
  if [ "$AEROSPACE_SERVICE_MODE_ENABLED" = true ]; then
    sketchybar --set workspaces_service_mode \
      label.drawing=on
  else
    sketchybar --set workspaces_service_mode \
      label.drawing=off
  fi
elif [ "$SENDER" = "aerospace_app_mode_enabled_changed" ]; then
  if [ "$AEROSPACE_APP_MODE_ENABLED" = true ]; then
    sketchybar --set workspaces_app_mode \
      label.drawing=on
  else
    sketchybar --set workspaces_app_mode \
      label.drawing=off
  fi
elif [ "$SENDER" = "aerospace_kitty_mode_enabled_changed" ]; then
  if [ "$AEROSPACE_KITTY_MODE_ENABLED" = true ]; then
    sketchybar --set workspaces_kitty_mode \
      label.drawing=on
  else
    sketchybar --set workspaces_kitty_mode \
      label.drawing=off
  fi
elif [ "$SENDER" = "aerospace_workspace_change" ]; then
  if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
    sketchybar --set $NAME \
      label.highlight=on \
      label.font="$LABEL_HIGHLIGHT_FONT"
  else
    sketchybar --set $NAME \
      label.highlight=off \
      label.font="$LABEL_FONT"
  fi
fi
