#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/tokyonight"

VOLUME_COLOR="$magenta"

sketchybar --add item volume right \
  --subscribe volume volume_change \
  --set volume \
  background.drawing=off \
  icon.drawing=on \
  icon.font="$ICON_BASE_FONT:Bold:15.0" \
  icon.color="$VOLUME_COLOR" \
  icon.padding_left=0 \
  icon.padding_right=0 \
  label.font="$LABEL_BASE_FONT:Regular:12.0" \
  label.color="$VOLUME_COLOR" \
  label.padding_left=4 \
  label.padding_right=6 \
  label.drawing=on \
  update_freq=60 \
  script="$PLUGIN_DIR/volume"
